version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: "/root/wait-for-it.sh db:5432 --timeout=0 -- echo Done!"
    depends_on:
      - 'db'
  db:
    build: ./docker/db
    ports:
      - '5432'
