version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: "/root/wait-for-it.sh db:5432 --timeout=0 -- ce"
    depends_on:
      - 'db'
    environment:
      - COVERAGE_EXPERIMENT_START
      - COVERAGE_EXPERIMENT_STEP
      - COVERAGE_EXPERIMENT_STOP
  db:
    build: ./docker/db
    ports:
      - '5432'
