version: "{branch} {build}"

notifications:
  - provider: Email
    to: []
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

build:
  verbosity: detailed

install:
  - powershell "cd lib; .\get-sqlfpc.ps1 -CICache"

build_script:
  - gradlew.bat assemble --no-daemon

test_script:
  - gradlew.bat :ga:check --no-daemon

branches:
  only:
    - master

cache:
  - '%USERPROFILE%\.gradle'
  - '%USERPROFILE%\.evosql-libs-cache'

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true

