version: "{branch} {build}"

notifications:
  - provider: Email
    to:
    - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --no-daemon

test_script:
  - gradlew.bat :ga:check --no-daemon

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true

